services:
  pb:
    build:
      context: .
      network: host
      dockerfile_inline: |
        FROM alpine:latest

        RUN apk add --no-cache \
            unzip \
            ca-certificates

        ARG PB_VERSION=0.22.18

        # download and unzip PocketBase
        ADD https://github.com/pocketbase/pocketbase/releases/download/v$${PB_VERSION}/pocketbase_$${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
        RUN unzip /tmp/pb.zip -d /pb/ pocketbase
    command: /pb/pocketbase serve --http=:8080
    ports:
      - 8080:8080
    volumes:
      - pb_data:/pb/pb_data:rw
      - ./pb_migrations:/pb/pb_migrations:ro
      - ./pb_hooks:/pb/pb_hooks:ro
    restart: unless-stopped
    networks:
      - default
    read_only: true

volumes:
  pb_data: